services:
  - type: web
    name: billing-system
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python -m gunicorn app:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: FIXED_ADMIN_EMAIL
        value: admin@techcraftery.com
      - key: FIXED_ADMIN_PASSWORD
        value: admin@123
      - key: FIXED_ADMIN_NAME
        value: admin
      - key: FIXED_ADMIN_USERID
        value: admin

